### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by rendaw** [terl/lazysodium-java#25]
This looks great, and I doubly agree that the other java implementations leave a lot to be desired.

I had a couple questions regarding secure memory that I didn't see addressed in the readme or faq.  I don't see anything about secure memory - what were your thoughts regarding that and how you implemented this library?  Any considerations regarding using Strings vs byte arrays?  Availability of the secure lock and allocation functions?

I'm using native Java crypto + bouncycastle in my current project, but I keep on hitting requirements like this so I'll probably be back soon.

**Comment by gurpreet-** [comment]
Hello @rendaw. Welcome to Lazysodium. Let's break down your questions a little.

> I don't see anything about secure memory - what were your thoughts regarding that and how you implemented this library?

I want to answer this question with a short example with three operations as follows:

```java
byte[] key = new byte[SecretBox.KEYBYTES]; // 1. Java byte allocation
cryptoSecretBoxKeygen(key); // 2. Passed to C native function
String keyStr = new String(key, StandardCharsets.UTF_8); // 3. Get key as string
```

Let's look at number **2** first. Lazysodium is just a wrapper on those functions provided by the underlying Libsodium C library. So anytime you do something like **2**, the underlying C library calls `sodium_memzero` which securely "zeroes out" byte arrays any intermediate byte arrays. So you're covered for number 2.

But for number **1** and number **3** erasing the memory is kind of difficult as those allocations are made in Java rather than C. Java, as you may well be aware, doesn't allow control over memory like C. Therefore, whilst performing **1** or **3** the byte arrays may have been moved around by the Java garbage collector or copied to virtual memory. It's up to the garbage collector to remove `key` and `keyStr` when no more references to those variables remain, but up until then, they remain held to the whims of the garbage collector.

You could zero out the `key` array manually using `sodium_memzero` or even set it to `byte[0]`. But as the garbage collector is a bit of a magic box, it's best to let it do its job 😄 

I by no means claim to be a Java memory expert so correct me if I'm wrong.

I'll add the [Secure Memory](https://download.libsodium.org/doc/helpers/memory_management.html) lower level functions.

> Any considerations regarding using Strings vs byte arrays?

If you mean in terms of secure memory and whether strings are better to use than byte arrays, then I say both are the same as a result of the above answer.

If you mean using Lazysodium's Lazy functions (which often take strings) as opposed to Lazysodium's Native functions (which often take byte arrays) then use whatever you prefer as they both achieve the same thing, it's just that the Lazy functions make it easier for devs to understand what's going on. However, if you are going to perform lower-level operations or manipulate byte arrays often then you're best off sticking to the Native functions.

> Availability of the secure lock and allocation functions?

As said above, I'll add these shortly 👍

**Comment by gurpreet-** [comment]
Added Secure Memory to the latest release [`2.3.0`](https://github.com/terl/lazysodium-java/releases/tag/2.3.0).

**Comment by rendaw** [comment]
Great, thanks for the thorough answer!  That seems reasonable - I've heard about gc moves before.  In any case it can't be worse than Java's native crypto operations.

The library additions are much appreciated.  TBH it sounds like you know much more about this than I do, but about the secure malloc/free - since the Pointer memory is entirely out of Java's hands they won't be implicitly copied/moved right?  Would it be possible/make sense to use those with other native functions (or maybe lazy functions) so the contents doesn't have to be transferred to Java's control as an intermediary?

(If it warrants a PR and you're busy I'd be glad to try making the changes myself)

**Comment by gurpreet-** [comment]
So basically what you're saying is you want to use `Pointer`s everywhere in order to avoid memory allocation in Java which therefore prevents the garbage collector doing all sorts of magic with the memory?

For example, here's the example [post above](https://github.com/terl/lazysodium-java/issues/25#issuecomment-394526872) but written in the `Pointer` form that I think you want:

```java
// Allocate bytes through libsodium
Pointer ptrToKeyBytes = lazySodium.sodiumMalloc(SecretBox.KEYBYTES);

// This function has been modified to
// take a Pointer instead of byte[]
cryptoSecretBoxKeygen(ptrToKeyBytes);

// Use sodiumFree to free the used bytes
lazySodium.sodiumFree(ptrToKeyBytes);
```

Is that correct?

**Comment by gurpreet-** [comment]
I've been reading into this and it seems like the idea of manually managing memory in JNA is a touchy subject.

You have threads like [this one](https://groups.google.com/forum/#!searchin/jna-users/free$20memory|sort:date/jna-users/0a10BsvE3RE/hBjG3k7ODgAJ) where some JNA maintainers and users [don't like the idea](https://groups.google.com/d/msg/jna-users/0a10BsvE3RE/IQ8yOOtkDgAJ) of memory management:

> I think using the GC to manage off-heap memory is a daft idea.  Note that ByteBuffers use phantom references for clean up already, and that can still be a PITA, and you can find countless 
discussions online in many different projects around use of sun.misc.Cleaner, etc. to support that view!  So, I do kind of agree with you that manual memory management methods (with caveats attached) makes sense, but I also think that anything relying on finalization or references for native memory management is a fundamentally flawed design - manage your own pool of native resources explicitly. 

On the other hand you have threads like [this one](https://groups.google.com/forum/#!searchin/jna-users/free$20memory|sort:date/jna-users/A-8vw6IAMjk/2cR0ZJJPmQIJ) where they are advocating use of `Native.free()` to free Java memory:

> That's my understanding.  E.g. if the native code allocates some memory with malloc() and returns it to your Java code, the Java code must explicitly call free() via JNA.

[Again, some are okay](https://groups.google.com/d/msg/jna-users/0a10BsvE3RE/kU24zY4fDgAJ) with it as long as you know what you're doing:

> Memory.disposeAll() exists, as does Memory.dispose() (which is protected). Use at your own risk.  You could certainly make your own class derived from Memory() which implements its own "dispose" to be more selective in its memory reclamation.

Here's [one](https://groups.google.com/forum/#!searchin/jna-users/free$20memory|sort:date/jna-users/Xy7Sm8Fb-Gc/CJ4DYo07NXEJ) from the lead maintainer backing up the claim that Java should garbage collect the memory:

> Any types generated from the Java side will be GC'd when no longer referenced. If you pass a byte[] to native code, it should *not* keep a reference to that memory outside that single function call.  If you need long-lived memory, you should use com.sun.jna.Memory or an NIO buffer. 

Here's [one from him again](https://groups.google.com/forum/#!searchin/jna-users/free$20memory|sort:date/jna-users/6msPJnZBpU8/caFqxRY4MSkJ) supporting JNA's self-management of memory, with some really helpful hints on how to manually free memory if you do want to go down that route.

> f you're managing your own memory, you need to a) keep a reference to the memory until you want to free it and b) free it [...] JNA's Memory is designed to be self-managing.

In addition to the useful information in all the threads linked above, [some](https://stackoverflow.com/questions/38337195/is-there-any-way-that-i-can-free-up-memory-in-the-java-code-that-is-generated-to/38337278) StackOverflow [posts](https://stackoverflow.com/questions/1744533/jna-bytebuffer-not-getting-freed-and-causing-c-heap-to-run-out-of-memory) provide some fantastically helpful information on memory management: 

> You could write basically a tiny library that just frees the memory for you, make the JNI interface for it, and pass the pointer to that. If you go this route then, depending on your OS, you might need to guarantee that your tiny free library's native code is running in the same process as the rest of the native code, or if not the same process then at least that the process you run it from has write access to the memory owned by the other code's process; this memory/process issue is probably not an issue in your case, but I'm throwing it out there for completeness.

**Comment by gurpreet-** [comment]
Overall, whilst I do think that this is a feature that increases security, it comes at a cost of convenience, which is against this library's ethos. Plus, once you do add this to this library, I'll have to maintain it and the inevitable questions such as `Why has my program segfaulted using Pointers and free()` will probably drive me crazy.

As a suggestion, because this library is wonderfully open source, you could extend Lazysodium into your own library (perhaps call it Megasodium 😃) by doing something like:

```sh
// Create a new library with Lazysodium as a dependency...
dependencies {
    implementation "com.goterl.lazycode:lazysodium-java:VERSION_NUMBER"
}
``

```java
// Add a new interface to the already existing one
public interface SecretBox.Raw {

        /**
         * Creates a random key using a Pointer instead of a byte array.
         * @param key The key which is of size {@link #KEYBYTES}.
         */
        void cryptoSecretBoxKeygen(Pointer key);

        // The rest of the functions using Pointer go here...

}
```

More details are outlined in the docs [here](https://docs.lazycode.co/lazysodium/~/edit/primary/contributions#adding-new-functions).

Then whenever this library gets an update, you could just do increase the `VERSION_NUMBER` and it would hopefully cause no conflicts.

Or you could simply fork the library and add whatever Pointer functions you want.

**Comment by rendaw** [comment]
Okay, thanks.  I think that's pretty reasonable, and the benefits of having pointers is probably limited.  I might fork someday :)... but not for a while.
