### ISSUE TITLE
Incompatible with Older Android Devices

### ISSUE THREAD

**Issue by m4dc4p** [terl/lazysodium-java#30]
When used with lazysodium-android, this library is only compatible with API 26+ devices (Android Oreo), due to usage of the `Paths`, `StandardCharsets` and other classes that were only recently added. Additionally, the `try-with-resources` pattern is not available prior to API 19.

A few small updates will make this library compatible back to Jelly Bean (API 16) and possibly even older devices.

**Comment by gurpreet-** [comment]
Hello @m4dc4p!

This is great! This also means that lazysodium-java can target Java 7 too as well as Android 16. I'd be glad to merge it 👍

**Comment by m4dc4p** [comment]
I forgot one other change - the `isPosixCompliant` method in `Nativeutils` also needs to be updated. I was going to just check if the OS was Windows. I'll submit a PR shortly. Apologies for forgetting that one!

**Comment by gurpreet-** [comment]
I wouldn't stress too much about making NativeUtils.java completely Android compliant as I exclude it from the Android side of things anyway:

```
sourceSets.main {
        java {
            srcDir "../lazysodium-java/src/main/java"
            exclude "com/goterl/lazycode/lazysodium/utils/NativeUtils.java" // Exclude!
            exclude "com/goterl/lazycode/lazysodium/SodiumJava.java"
            exclude "com/goterl/lazycode/lazysodium/LazySodiumJava.java"
        }
}
```

**BUT**, even so, it would be nice to have `NativeUtils.java` completely support Java 7, which is the main motivation for merging your PR.

So yes, you don't really need to do anything else as NativeUtils is Java 7 compliant and also now Android compliant (because it's already getting excluded) 😄

**Comment by m4dc4p** [comment]
There's an issue for that! :) https://github.com/terl/lazysodium-android/issues/8
