### ISSUE TITLE
Consider a more politically correct - enterprise friendly name for the library

### ISSUE THREAD

**Issue by cyrilmhansen** [terl/lazysodium-java#38]
Hi,

I currently work as freelancer for a communication company and I am looking for open source libraries to implement AEAD for an IOT project.

Technically your work is very interesting for my Java team but I am embarrassed by the name of the project which sounds non professionnal. Sorry if this sounds killjoy but my understanding is that your dedicated work deserve real feedback.

Regards,
CMH

**Comment by gurpreet-** [comment]
Hello @cyrilmhansen,

Your feedback is much appreciated. I am open to receiving any kind of feedback. I chose the name because I wanted something effortless built on Libsodium - thus Lazysodium as a name was chosen. It helps to have SEO keywords related to the Libsodium project too.

I can totally see how it would be embarrassing because I've worked in enterprise myself.

I'm open to suggestions about the name. What name would you suggest? Community suggestions also welcome.

**Comment by cyrilmhansen** [comment]
The list on the bindings section of Libsodium documentation is  uninspiring. I notice that most names do not contain spaces.

My understanding is that the project name should keep some self description value (reference to libsodium or salt and Java /Android) and at the same time conveys a positive impression of quality / productivity for non crypto specialists. Of course existing projet names or too close variants should be avoided.

(so names to avoid : ​libsodium-jna​ libstodium​ robosodium​ libsodium-JNI​
ConsenSys Cava jsodium​ Kalium​ sodium-jni​)


Some names I could think of in a few minutes: I may be very influenced by technical books names...

easysodium-java, easysodium-android
sodium4j [-android]
practical-sodium[-java|-android]
pragmatic-sodium[-java|-android]
productive-sodium[-java|-android]
fruitful-sodium[-java|-android]

Regards,

Cyril

**Comment by gurpreet-** [comment]
Hello again. I really like Easysodium.

But, I'm having second thoughts. It's currently too time-consuming for me to move to a different name. Plus, there isn't enough funding on this project so I'm not incentivised enough to move to a different name.

Hope you can understand my viewpoint Cyril.
