### ISSUE TITLE
Missing resource-loader dependency

### ISSUE THREAD

**Issue by MakarovS** [terl/lazysodium-java#55]
Hi! In 4.1.0 release you added a dependency to `com.github.libly:resource-loader:1.3.3`, but it is not published on Maven Central. I see that you are a contributor of that library as well - could you please publish it?

**Comment by gurpreet-** [comment]
Hi @MakarovS,

Sure. I wanted to move away from Jitpack as it does not have the precision that Bintray has. So I have uploaded it to Bintray https://bintray.com/libly/maven/resource-loader and I have submitted it for reviewal for going into Maven Central. So it should be in there very shortly.

**Comment by mabrcosta** [comment]
Hi @gurpreet-,

Can you update the documentation to include this dependency and where to get it? 
I could only get the latest version (4.1.0) working because you vaguely mention Jitpack in the previous comment and tried to check if the required version was somehow still available there.

It should also be noted that with the namespace change from `com.github.libly` to `libly.co` it rendered the latest released version of lazysodium-java unable to use Bintray repo.

**Comment by gurpreet-** [comment]
So the problem was that I did not add version `1.3.3` of resource-loader to jCenter which is what version `4.1.0` depended on! How silly.

I have fixed it in the latest version `4.2.0` by adding version `1.3.4` of resource-loader to jCenter. You can use Bintray or jCenter to get lazysodium. Bintray always has the latest version faster than jCenter.

**Comment by gurpreet-** [comment]
So this means you need to include `jCenter` in you repositories section too. Something like the following should suffice:


```groovy
// Top level build file 
repositories {
    jcenter()
    maven {
        url  "https://dl.bintray.com/terl/lazysodium-maven"
    }
}

// Add to dependencies section in app level build file
dependencies {
    implementation "com.goterl.lazycode:lazysodium-java:VERSION_NUMBER"
}
```

**Comment by MakarovS** [comment]
@gurpreet- Thanks!

**Comment by gurpreet-** [comment]
Okay so this one has been solved. Just issue #56 that remains outstanding.
