### ISSUE TITLE
Missing resource-loader dependency

### ISSUE THREAD

**Issue by dmitry-timofeev** [terl/lazysodium-java#71]
resource-loader is neither specified as a project dependency so that it can be fetched by the build system, nor is bundled in the lazysodium-java distribution, leading to a runtime error:

```
java.lang.NoClassDefFoundError: co/libly/resourceloader/SharedLibraryLoader
```

**Version:** 4.2.5

### Workaround

It is possible to overcome the problem by specifying an explicit dependency on resource-loader. However, that might eventually result in an incompatible combination of lazysodium and resource-loader versions in the user projects.

**Comment by gurpreet-** [comment]
You are correct, this is becoming a pain in some of my other projects too. 

One way of handling this is to add `resource loader` as a JAR rather than a gradle dependency. My initial tests into this solution have been unsuccessful; it seems doing it that way causes resource loader to no longer find resources at all. Perhaps you might see different results?

Another way is instead of using maven as a central repository force all projects to use `resource loader`'s bintray repository. I had indeed initially done this but enterprise preferred maven central.

**Comment by gurpreet-** [comment]
Try release [`4.2.6`](https://github.com/terl/lazysodium-java/releases/tag/4.2.6). I think I fixed it.

**Comment by dmitry-timofeev** [comment]
It works, thank you a lot!

Yes, Maven Central takes quite some time to make the artifacts available :-) 

>  I had tested this on an empty Java project and it worked, not sure why it isn't for you 🤔

Can't say definitely, but it might have been installed locally in your `~/.m2/repository`.

**Comment by gurpreet-** [comment]
Thanks for your help once again! 🙂
